# Generated by Django 5.1.6 on 2025-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.IntegerField()),
                ('disposal_time', models.TimeField()),
                ('quantity_initial', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
            ],
        ),
    ]
