# Generated by Django 5.1.6 on 2025-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0002_pill_pill_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='pill_slot',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
