# Generated by Django 5.1.6 on 2025-03-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0002_pill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
