# Generated by Django 5.1.6 on 2025-03-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0003_pill_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='image',
            field=models.ImageField(blank=True, default='pill.jpeg', null=True, upload_to='pill_images/'),
        ),
    ]
