# Generated by Django 5.1.6 on 2025-02-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0004_alter_pill_pill_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='pill_slot',
        ),
    ]
