# Generated by Django 5.1.6 on 2025-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0006_pill_taken_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
    ]
