# Generated by Django 4.2.16 on 2025-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0006_pill_pill_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='taken_today',
            field=models.IntegerField(default=0),
        ),
    ]
