# Generated by Django 4.2.16 on 2025-04-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0007_pill_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='slot_angle',
            field=models.IntegerField(default=0),
        ),
    ]
