# Generated by Django 5.1.6 on 2025-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0008_pill_slot_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caretaker', 'Caretaker')], default='patient', max_length=10),
        ),
    ]
