# Generated by Django 5.1.6 on 2025-04-13 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillPopperPro', '0009_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caretakers',
            field=models.ManyToManyField(blank=True, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
