WEBSOCKET_URL = "ws://18.223.133.87/pillPopperPro/data/"
RELEASE_PILL_PATH = "Sample.wav"
REFILL_PILL_PATH = "Sample.wav"
FINISH_DISPENSING_PATH = "Sample.wav"
INVALID_DISPENSING_PATH = "Sample.wav"
NOT_DISPENSED_PATH = "Sample.wav"
LOAD_CELL_ERROR = 30 # 30mg